version: '3.8'

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16


services:
  db:
    image: mysql:latest
    container_name: mysql_wotw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: ig2i
      MYSQL_PASSWORD: ig2i
    networks:
      my_network:
        ipv4_address: 172.18.0.2

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: