networks:
  wotw-network:
    driver: bridge


services:

  wotw-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: wotw-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wotw
      MYSQL_USER: wotw
      MYSQL_PASSWORD: wotw
    networks:
      - wotw-network

    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql

  wotw-app:
    build:
      context: .
      dockerfile: Dockerfile.app
      #dockerfile: Dockerfile.prod
    container_name: wotw-app
    networks:
      - wotw-network
    ports:
      - "5000:5173"
    depends_on:
      - wotw-db
    volumes: # Delete in production environment
      - ./app:/app
      - /app/node_modules # This is to prevent the node_modules folder from being overwritten by the volume
      - /app/.svelte-kit # This is to prevent the .svelte-kit folder from being overwritten by the volume
      - /app/build # This is to prevent the .svelte-kit folder from being overwritten by the volume

volumes:
  db_data: