version: '3.8'

networks:
  wotw-network:
    driver: bridge


services:

  wotw-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: wotw-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wotw
      MYSQL_USER: wotw
      MYSQL_PASSWORD: wotw
    networks:
      - wotw-network

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  wotw-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: wotw-app
    restart: always
    networks:
      - wotw-network
    ports:
      - "5172:5173"
    depends_on:
      - wotw-db
    volumes:
      - ./app:/app

volumes:
  db_data: